server:
  port: 3002

#eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${random.uuid}
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka/
#    fetch-registry: true
#    register-with-eureka: true
  #  application:
  #    name: remote-code-execution-server-service
  #  config:
  #    import: optional:configserver:config-server
  #  cloud:
  #    config:
  #      discovery:
  #        enabled: true
  #        service-id: config-server
  #host.docker.internal
spring:
  cache:
    redis:
      time-to-live: 20
  rabbitmq:
    host: host.docker.internal
    port: 5672
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
    url: jdbc:postgresql://host.docker.internal:5432/consumer-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
      use_sql_comments: false
      type: all
      disableConnectionTracking: true
logging:
  level:
    org:
      hibernate:
        SQL : DEBUG


