server:
  port: ${PORT:3002}
hostname: ${HOSTNAME:localhost:3002}
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka

spring:
  application:
    name: remote-code-execution-server-service
  cache:
    redis:
      time-to-live: 20
  rabbitmq:
    host:  ${RABBITMQ_URL}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${BDD_USERNAME}
    password: ${BDD_PASSWORD}
    url: jdbc:postgresql://${BDD_URL}?useSSL=false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
      use_sql_comments: false
      type: all
      disableConnectionTracking: true
  redis:
      host: ${REDDIS_URL:host.docker.internal}
      port: ${REDDIS_PORT:6379}
jwt:
  header: Authorization
  secret:  ${JWT_SECRET}
  expiration: 86400

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.assignment: DEBUG
